@startuml
!include SongBoard_Context_simple.puml
skinparam componentStyle uml2

title SongBoard Detailed Context Diagram

rectangle "This detailed context diagram contains also \nthe elements that might in future influence \nthe development of SongBoard." <<note>> as topnote {
}

skinparam rectangle{
BackgroundColor<<note>> LemonChiffon
BorderColor<<note>> Red
}


topnote -[hidden]-> ac


node AudioInterface {

}

node DAW-UI  as dui {

}

node MIDI-Keys  as mk{

}

node Mixer as mixer {
     
}

node "Large Diaphragm \nCondenser Microphone" as mic {
}

node "Dynamic Microphone" as mic2 {
}

node "Podcast Microphone" as mic3 {
}

node ActiveSpeaker-L as asl {

}

node ActiveSpeaker-R as asr {

}

node "Guitar Amp Modeller & Fx" as FM3 {
}

node "Electric Guitar" as guitar {
}

node "Drum Machine" as bb {
}


AudioInterface -- MacBookPro : USB
dui -- MacBookPro : USB
mk -- dui : USB
AudioInterface --> mixer : line_stereo
mixer --> AudioInterface : line_left
mixer --> AudioInterface : line_right
mic -- AudioInterface : XLR 48V
mic2 --> mixer : XLR
mic3 --> MacBookPro : USB
FM3 --> mixer : XLR left
FM3 --> mixer : XLR right
guitar --> FM3
mixer -- asl : XLR
mixer -- asr : XLR
bb --> mixer : line_left
bb --> mixer : line_right

dui ..> lpx : controls


@enduml