@startuml

skinparam componentStyle uml2

title SongBoard Context Diagram


:AmateurComposer:
:SongBoardDeveloper:

 
rectangle "SongBoard" <<application>> as sb {
    cloud SongBoardUI { 
    } 
    (Find out the right workflow \n for composing songs) as ucdw
    SongBoardUI .. ucdw
} 

note top of sb
    Prototype application.
    Might make a iOS app out 
    of it later if it works.
end note

note top of sb
    Implementation in Python
    using tkinter for GUI 
    for fast prototyping.
end note

node MacBookPro {
cloud MacOS {
}
 note left of MacOS : version >= 10.14.6

cloud Python {
 }
 note left of Python: version >= 3.8.2

cloud LogicProX as lpx {
 }
 note left of lpx: version >= 10.5.1

} 

node AudioInterface {

}

node DAW-UI  as dui {

}

node MIDI-Keys  as mk{

}

node Mixer as mixer {
     
}

node "Large Diaphragm \nCondenser Microphone" as mic {
}

node "Dynamic Microphone" as mic2 {
}

node "Podcast Microphone" as mic3 {
}

node ActiveSpeaker-L as asl {

}

node ActiveSpeaker-R as asr {

}

node "Guitar Amp Modeller & Fx" as FM3 {
}

node "Electric Guitar" as guitar {
}

node "Drum Machine" as bb {
}


MacOS -[hidden]-> Python
Python -[hidden]-> lpx

AmateurComposer --> SongBoardUI : use to compose
sb -down-> MacBookPro: runs on
AmateurComposer ..> MacBookPro : owns
AudioInterface -- MacBookPro : USB
dui -- MacBookPro : USB
mk -- dui : USB
AudioInterface --> mixer : line_stereo
mixer --> AudioInterface : line_left
mixer --> AudioInterface : line_right
mic -- AudioInterface : XLR 48V
mic2 --> mixer : XLR
mic3 --> MacBookPro : USB
FM3 --> mixer : XLR left
FM3 --> mixer : XLR right
guitar --> FM3
mixer -- asl : XLR
mixer -- asr : XLR
bb --> mixer : line_left
bb --> mixer : line_right

SongBoardDeveloper --> ucdw : work on

dui ..> lpx : controls


@enduml