@startuml
!include SongBoard_UseCases.puml
title SongBoard - Use Cases with Context Diagram


rectangle LogicProX <<application>> {
    (Import Song from SongBoard) as impo
    (Record tracks with real \ninstruments and vocals)
    (Mix tracks)
    (Master song)
}

AmateurComposer --> LogicProX

expo ..> impo

@enduml
